# Generated by Django 2.2.3 on 2019-07-30 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('terrain', models.CharField(blank=True, max_length=255)),
                ('elevation', models.IntegerField(default=0)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('e_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='east', to='mud_explorer.Room')),
                ('n_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='north', to='mud_explorer.Room')),
                ('s_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='south', to='mud_explorer.Room')),
                ('w_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='west', to='mud_explorer.Room')),
            ],
        ),
    ]
