# Generated by Django 2.2.3 on 2019-07-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mud_explorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='e_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='west', to='mud_explorer.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='n_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='south', to='mud_explorer.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='s_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='north', to='mud_explorer.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='w_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='east', to='mud_explorer.Room'),
        ),
    ]
