# Generated by Django 2.2.3 on 2019-08-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mud_explorer', '0002_auto_20190730_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='e_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='elevation',
        ),
        migrations.RemoveField(
            model_name='room',
            name='n_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='s_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='terrain',
        ),
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
        migrations.RemoveField(
            model_name='room',
            name='w_to',
        ),
        migrations.AddField(
            model_name='room',
            name='e',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='s',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='w',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
